
meta_title: "12restaurants: Good Food is a Principle"
meta_description: "The best dinners are all about bringing together good food with good company--we help you find the food; you bring the company."
meta_image: "banner-image.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@lewagonadam" # indispensable pour les Twitter Cards



