
meta_title: "12restaurants: Good Food is a Right"
meta_description: "Dining is about bringing together good food with good company--we help you find the food; you bring the company, to enjoy great dinners in your city with a discount."
meta_image: "banner-image.jpg" # Une image dans votre dossier app/assets/images/
# twitter_account: "@nomdevotrecompte" # indispensable pour les Twitter Cards
# to implement soon



