# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 365d20b1d71032c3c86e810204dafa75f7d4935ef9c912a755ec4802a4413bbb828b9b37d61b3239a24480d7c8b3447049f6a25c0556943ea434e247ad8114e8

test:
  secret_key_base: b698500bbde9a9604b0ad4abab77741f827563f162007e394b906783fcd300f715bd4f2da60ed61dce8b64bde8d54bb8ab7f8d1b9061822e3f4fe7b45b176f4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
